### ISSUE TITLE
Broken Styles

### ISSUE THREAD

**Issue by EmanDev** [RafaelDeJongh/h5ai-dark-theme#2]
Title says it all.
I followed exactly the instructions and rechecked. Seems ok, however...

![bug](https://user-images.githubusercontent.com/25047362/71316234-776d1f80-24a7-11ea-8594-681b3dea8188.png)

**Comment by Evoley** [comment]
Weird. I'm getting the same thing.

**Comment by Drakonas** [comment]
I'm having the same issue. @EmanDev Did you end up fixing this?

**Comment by EmanDev** [comment]
> I'm having the same issue. @EmanDev Did you end up fixing this?

This was 2 years ago. But I remember doing the following:

1. Clear browser cache or use a newly installed browser.
2. Redoing everything related on h5ai. Basically, if you have h5ai on your server, remove it and then add it back again then implement the css style for dark mode. 

I'll also link repo just in case... Here's a working css style (but both are probably the same): https://github.com/EmanDev/emandev-downloads/blob/master/web/_h5ai/public/css/styles.css

**Comment by Drakonas** [comment]
> > I'm having the same issue. @EmanDev Did you end up fixing this?
> 
> This was 2 years ago. But I remember doing the following:
> 
> 1. Clear browser cache or use a newly installed browser.
> 2. Redoing everything related on h5ai. Basically, if you have h5ai on your server, remove it and then add it back again then implement the css style for dark mode.
> 
> I'll also link repo just in case... Here's a working css style (but both are probably the same): https://github.com/EmanDev/emandev-downloads/blob/master/web/_h5ai/public/css/styles.css

Thanks so much for the help! I updated to 0.31.0 by Gluby and was able to use your CSS after merging the changes from 0.31.0 and the additions you made.

Thanks. :)

**Comment by RafaelDeJongh** [comment]
@Drakonas & @EmanDev

Not entirely sure why it would cause such an issue like the one from op's original post. Is this still the case? If so it looks to me like some part of the main style isn't properly loading due to a cache conflict perhaps?

Or were there any structural changes I'm not aware off? I've personally switched to using a litespeed Web server and don't utilise h5ai anymore but I could always look into it if anyone wants it.

**Comment by Drakonas** [comment]
> Not entirely sure why it would cause such an issue like the one from op's original post. Is this still the case? If so it looks to me like some part of the main style isn't properly loading due to a cache conflict perhaps?
> 
> Or were there any structural changes I'm not aware off? I've personally switched to using a litespeed Web server and don't utilise h5ai anymore but I could always look into it if anyone wants it.


I originally didn't know you have to precompile the sources rather than just copy-paste. It's very possible that a while back I was copying only components that had their dates change and may have placed something that actually needed to be precompiled.

Strangely, it did not catch that they weren't compiled, even though there seems to be a check for it in the index.php.

I do have a backup of the folder before I fixed it, if you'd like to check into the issue and reproduce it. I'm really not sure if it's the CSS style or not.
[_h5ai.zip](https://github.com/RafaelDeJongh/h5ai-dark-theme/files/8567272/_h5ai.zip)
